### ISSUE TITLE
data type "string" not understood 

### ISSUE THREAD

**Issue by manishprasadthapliyal** [strongio/keras-elmo#2]
while fitting the model i am getting following error
**data type "string" not understood** 
Traceback (most recent call last):
  File "/home/manish/Downloads/NER-latest/NER/Semi_Supervised/train.py", line 246, in <module>
    batch_size=32)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1042, in fit
    validation_steps=validation_steps)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2661, in __call__
    return self._call(inputs)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2614, in _call
    dtype=tensor.dtype.base_dtype.name))
  File "/root/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: data type "string" not understood

**Comment by mikkokotila** [comment]
To avoid confusion, I'm retracting the original comment and instead provide the solution > 

This was an issue with Keras coming from the way tf was calling numpy, and you can fix it simply by: 

`pip install -U git+https://github.com/keras-team/keras.git`

This should do it.

**Comment by nreimers** [comment]
Hi @mikkokotila @manishprasadthapliyal 

I had the same issues. Instead of tensorflow hub, I used AllenNLP to compute the ELMo embeddings.

I created a Git repository where I integrate ELMo representations into a BiLSTM-CRF architecture for sequence tagging:
https://github.com/UKPLab/elmo-bilstm-cnn-crf

In the next days I will create more (educational) material how to extend your keras experiments with ELMo embeddings. Feedback is welcome.

**Comment by nreimers** [comment]
I modified the example here and made an IPython notebook how to use ELMo embeddings for sentence / document classification:
https://github.com/UKPLab/elmo-bilstm-cnn-crf/blob/master/Keras_ELMo_Tutorial.ipynb

It saves a lot of computational time if we compute the ELMo embeddings only once as a pre-processing step and store the embeddings in a big matrix that is fed to the neural network. This reduces the training time for an epoch to about 1 second.

**Comment by jacobzweig** [comment]
Thanks for the update @mikkokotila and @nreimers.
